kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Values.name}}
  labels:
    run: {{.Values.name}}
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: {{.Values.name}}
  template:
    metadata:
      labels:
        run: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{.Values.guillotinaPort }}
        command: ["guillotina"]
        args:
          {{  range .Values.arguments }}
            - {{ . }}
          {{ end }}
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /config.json
          subPath: config.json
      volumes:
      - name: config
        configMap:
          name: config