# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
language: python
sudo: required
addons:
  postgresql: 9.6
matrix:
  include:
    - name: Python 3.6, Dummy DB
      python: 3.6
      env: DATABASE=DUMMY
    - name: Python 3.6, PG 9.6
      python: 3.6
      env: DATABASE=postgres
    - name: Python 3.6, Cockroachdb
      python: 3.6
      env: DATABASE=cockroachdb
    - name: Python 3.7, Dummy DB
      python: 3.7
      env: DATABASE=DUMMY
    - name: Python 3.7, PG 9.6
      python: 3.7
      env: DATABASE=postgres
    - name: Python 3.7, PG 9.6 (db_schema=custom)
      python: 3.7
      env:
       - DATABASE=postgres
       - DB_SCHEMA=custom
    - name: Python 3.7, Cockroachdb
      python: 3.7
      env: DATABASE=cockroachdb

services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install Cython==0.27.3
  - pip install -r requirements.txt
  - pip install -e .[test]
  - pip install flake8==3.7.7 codecov mypy==0.670 mypy-zope
  - sleep 5
script:
  - flake8 guillotina --config=setup.cfg
  - mypy guillotina/
  - pytest -s --cov=guillotina -s --tb=native -v --cov-report term-missing --cov-append guillotina
after_success:
  - codecov

deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
