---
databases:
  d:
    storage: DUMMY
  df:
    storage: DUMMY_FILE
    filename: dummy_file.db
host: 0.0.0.0
port: 8080
root_user:
  password: root
cors:
  allow_origin:
  - "*"
  allow_methods:
  - GET
  - POST
  - DELETE
  - HEAD
  - PATCH
  - PUT
  allow_headers:
  - "*"
  expose_headers:
  - "*"
  allow_credentials: true
  max_age: 3660
utilities: []
jsapps:
  +admin: guillotina:static/executioner
static:
  assets: guillotina:static/assets
jwt:
  secret: secret
