kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    run: {{ .Values.name }}
spec:
  ports:
  - protocol: TCP
    port: {{.Values.guillotinaPort}}
    targetPort: {{.Values.guillotinaPort}}
    nodePort: {{.Values.exposedPort}}
  selector:
    run: {{ .Values.name }}
  type: NodePort
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
