replicaCount: 2

name: guillotina

image:
  repository: guillotina/guillotina
  tag: latest
  pullPolicy: IfNotPresent

exposedPort: 32354

serviceType: NodePort

resources: {}

guillotinaPort: 8080

arguments: []

app_settings:
  debug: true
  applications:
    - guillotina.contrib.catalog.pg
    - guillotina.contrib.swagger
  databases:
    db:
      storage: postgresql
      transaction_strategy: resolve_readcommitted
      dsn: postgresql://postgres@localhost:5432/guillotina
      pool_size: 40
      read_only: false
      statement_cache_size: 100
      max_cached_statement_lifetime: 300
      autovacuum: false
    db-custom:
      storage: postgresql
      dsn: postgresql://postgres@localhost:5432/guillotina
      objects_table_name: foobar
      blobs_table_name: foobar_blobs
  storages:
    storage:
      storage: postgresql
      transaction_strategy: resolve
      dsn: postgresql://postgres@localhost:5432
      pool_size: 40
      read_only: false
  host: 0.0.0.0
  port: 8080  
  root_user:
    password: root
  cors:
    allow_origin:
    - "*"
    allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - PUT
    allow_headers:
    - "*"
    expose_headers:
    - "*"
    allow_credentials: true
    max_age: 3660
  utilities: []
  jsapps:
    +admin: guillotina:static/executioner
  static:
    assets: guillotina:static/assets
  logging:
    version: 1
    formatters:
      default:
        format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      default:
        class: logging.StreamHandler
        level: DEBUG
    loggers:
      guillotina:
        level: DEBUG
        handlers:
          - default
        propagate: 1
